In [ ]:
"""Numpy is a python library used for scientific computing
numpy array is a grid of values containg info about the raw data i.e how to locate an element and how to interpret an element.
advantage of numpy over list is
1.consumes less memory bcz of homogenity and contiguous block of allocation
2.faster than list for performing various mathematical operations

pip install numpy #installation
import numpy as np #importing"""

In [4]:
import numpy as np
%timeit x=np.array([1,2,3,4]) #for knowing the execution time
x=np.array([1,2,3,4])
print(x)
print(type(x))

740 ns ± 54.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
#dimension
x=np.array([1,2,3]) #1D array
y=np.array([[1,2,3]])  #2D array
z=np.array([[[1,2,3]]]) #3D array
print(x.ndim) 
print(y.ndim)
print(z.ndim)
a=np.array([1,2,3],ndmin=9)  #creating multidimensional array
print(a)
print(a.ndim)

1
2
3
[[[[[[[[[1 2 3]]]]]]]]]
9


# creating numpy using numpy functions

In [12]:
#arary with zeros
a=np.zeros(4) #1D
print(a)
b=np.zeros((3,4)) #2D
print(b)

#array with ones
a=np.ones(4) #1D
print(a)
b=np.ones((3,4)) #2D
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
#range
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a=np.empty(10)  #empty array
print(a)

#diagnol
a=np.eye(4)
print(a)
print(" ")
#linespace
a=np.linspace(1,10,num=4)  #four numbers with equal difference in between 1 and 10
print(a)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.22521816e-307
 2.67017826e-306 1.42413555e-306 1.78019082e-306 1.37959740e-306
 6.23057349e-307 1.42419530e-306]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 
[ 1.  4.  7. 10.]


# craeting numpy array using random numbers

In [22]:
a=np.random.rand(4)  #generate random numbers in between 0 and 1
print(a)
a=np.random.randn(4)  #generate random numbers close to zero which may be positive or negative
print(a)
a=np.random.ranf(4)  #generate random numbers in interval 0.0 and 1.0
print(a)
a=np.random.rand(1,4)  #generate random numbers in between the given range
print(a)

[0.95426303 0.73677007 0.85090701 0.08124293]
[ 0.89280076  0.30035965 -1.05116597 -0.18843378]
[0.97635427 0.36075847 0.66274627 0.77306543]
[[0.94815561 0.94903577 0.30666091 0.82676307]]


# arithmatic operations

In [5]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[0 0 0 0]
[  1   4  27 256]
[1 0 0 0]


# arithmetic functions

In [10]:
a=np.array([1,2,3,4])
print(np.min(a),np.argmin(a)) #argmin/argmax defines the position
print(np.max(a),np.argmax(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.cumsum(a)) # cumulative sum
a=np.array([[2,0,9,3],[8,9,6,2]])
print(np.min(a,axis=0)) #colwise
print(np.max(a,axis=1)) #rowwise

1 0
4 3
[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]
[2 0 6 2]
[9 9]


In [16]:
# shape and reshape
a=np.array([1,2,3,4,5,6])
print(a.shape)
b=np.array([1,2,3,4,5,6 ],ndmin=10)
print(b.shape)
print(a.reshape(2,3))

(6,)
(1, 1, 1, 1, 1, 1, 1, 1, 1, 6)
[[1 2 3]
 [4 5 6]]


In [17]:
#braodcasting
x=np.array([[1],[2]])   # rows common 2&2 hence 2 cols are 1&3 max is 3 hence result is (2x3)
print(x.shape)
y=np.array([[1,2,3],[4,5,6]])
print(y.shape)
print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [6 7 8]]


In [27]:
#indexing and slicing
a=np.array([1,2,3,4])
print(a[2])
print(a[-2])
b=np.array([[1,3],[6,7]])
print(b[1,0])
c=np.array([[[1,2,3],[4,5,6]]])
print(c[0,1,0])
d=np.array([1,2,3,4,5,6,7])
print(d[2:6:2]) # start stop step
print(d[:6])
e=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(e[1,1:])

3
3
6
4
[3 5]
[1 2 3 4 5 6]
[ 7  8  9 10]


In [38]:
#iterating
a=np.array([1,2,3,4])
for i in a:
    print(i)
for i in np.nditer(a):
    print(i)
for i in np.ndenumerate(a):
    print(i)

1
2
3
4
1
2
3
4
((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)


In [35]:
var=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) # for n-dimension n-forloops can be used

for i in var:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [39]:
#copy and view
a=np.array([1,2,3,4])
b=a.copy()   #changes made to copy doesnot reflect the main array
print(a)
a=np.array([1,2,3,4])
b=a.view() #changes made to view reflect the original array
print(a)


[1 2 3 4]
[1 2 3 4]


In [48]:
#joining of ararys
a=np.array([1,2,3,4])
b=np.array([9,8,7,6])
print(np.concatenate((a,b)))
print(np.stack((a,b)))
print(np.hstack((a,b))) #rowwise
print(np.vstack((a,b))) #colwise
print(np.dstack((a,b))) #heightwise

[1 2 3 4 9 8 7 6]
[[1 2 3 4]
 [9 8 7 6]]
[1 2 3 4 9 8 7 6]
[[1 2 3 4]
 [9 8 7 6]]
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [45]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print()
print(b)
print()
print(np.concatenate((a,b)))
print()
print(np.concatenate((a,b),axis=0))
print()
print(np.concatenate((a,b),axis=1))
print()


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



In [49]:
# splitting of arrays
a=np.array([1,2,3,4,5,6])
print(np.array_split(a,2)) # splitting an array a into two arrays

[array([1, 2, 3]), array([4, 5, 6])]


# array functions

In [51]:
#search
a=np.array([1,2,3,4])
print(np.where(a==4))
print(np.where(a%2==0)) # search for even numbers


(array([3], dtype=int64),)
(array([1, 3], dtype=int64),)


In [54]:
#searchsorted   tells where the element can be inserted
a=np.array([1,2,3,4,6,7,8])
print(np.searchsorted(a,5,side="left"))
print(np.searchsorted(a,9,side="right"))

4
7


In [55]:
#sort
a=np.array([2,1,5,3,7,5,6,9])
print(np.sort(a))

[1 2 3 5 5 6 7 9]


In [56]:
#filter(getting some elements out and creating a new array out of them)
a=np.array([1,2,3,4])
f=[True,True,False,False]
print(a[f])


[1 2]


In [64]:
#shuffle
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)
#unique
a=np.array([1,2,2,3,5,6,7,3,4,5])
print(np.unique(a,return_counts=True))
#resize
print(np.resize(a,(2,3)))
print(a.flatten())

[2 4 3 1 5]
(array([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 2, 1, 2, 1, 1], dtype=int64))
[[1 2 2]
 [3 5 6]]
[1 2 2 3 5 6 7 3 4 5]


In [67]:
#insert
a=np.array([1,2,3,4])
print(np.insert(a,(2,3),50)) # list,pos,ele  doesnot allow float
print(np.append(a,6.5)) #appends at end

[ 1  2 50  3 50  4]
[1.  2.  3.  4.  6.5]


In [69]:
#delete
a=np.array([1,2,3,4])
print(np.delete(a,2)) #list,pos

[1 2 4]
